// NOTE: This is a struct that will contain only the values needed 
// to create a User.

// So it will not include all of the fields that a User would have.
// E.g. The id field is missing because if you check the file:
// `migrations/0001_users_table.sql`, that field / column data will be
// generated by the Postgres database

use serde::Deserialize;

// I'm adding the `Deserialize` functionality from `serde` so that data
// that is received in JSON format (when a CREATE request is made to the API),
// will  be automatically converted in Rust data that can be stored 
// in this struct.
#[derive(Deserialize)]
pub struct UserPayLoad {
    pub name: String,
    pub email: String
}
