// NOTE: This is a struct that will contain only the values needed 
// to create a User.

// So it will not include all of the fields that a User would have.
// E.g. The id field is missing because if you check the file:
// `migrations/0001_users_table.sql`, that field / column data will be
// generated by the Postgres database
pub struct UserPayLoad {
    pub name: String,
    pub email: String
}
